### ISSUE TITLE
Ivory BBS character encoding messed up at 2400 baud

### ISSUE THREAD

**Issue by kcasteels** [FozzTexx/tcpser#1]
I've been trying to get this new version of tcpser to work with Ivory BBS. I run a BBS and it current works with the older version at 1200 baud, but wont begin the session with a call on 2400 baud.  Your new version does answer the call at 2400 baud and starts the session, so the changes you made have been a  major improvement.  Unfortunately the character encoding is messed up now.  Have you made a change to the encoding, or to anything that would affect it, in this new version? Thanks!

**Comment by FozzTexx** [comment]
Can you describe what you mean by "messed up"? Data is just passed through, but if you're sending AT commands with the high bits set then tcpser will detect that you're using parity and will strip data to 7 bits and regenerate parity through the serial port. Make sure you have your communications set to 8N1.

**Comment by kcasteels** [comment]
By messed up I mean the characters displayed don't correspond to what they should.  For the letters, sometimes the case is inverted, but they always come through properly.  The PETSCII symbols generally don't correspond to what they should.  As the parity is what you've added to the code, I guess this is where the problem lies.  I'll investigate further.

**Comment by FozzTexx** [comment]
It sounds like you're sending the AT commands with even/odd/mark parity instead of space or no parity.

**Comment by kcasteels** [comment]
That's entirely possible. Unfortunately the source code for Ivory BBS was lost long ago so I don't know exactly what its doing.  The BBS definitely sends AT commands to the modem (tcpser) when it starts up.

**Comment by kcasteels** [comment]
Any chance of putting in support for even/odd/mark parity?  I'm happy to help in anyway possible. I've been looking at the code but need time to understand whats going on... If you want I could also send you the BBS software I'm using.  Your work on this is much appreciated!

**Comment by FozzTexx** [comment]
I already put in parity support. If your BBS is sending the wrong parity then you'll need to fix the BBS. Maybe I can look at the BBS over the weekend if you send me the software.

**Comment by kcasteels** [comment]
```
                                                                                  I dont think its a problem of the BBS sending the wrong parity, but maybe its an ASCII/PETSCII problem that is causing something to go wrong. I cant change the BBS code, so I'll try and mod tcpser to work for me.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: FozzTexxSent: Friday, July 22, 2016 17:04To: FozzTexx/tcpserReply To: FozzTexx/tcpserCc: Kevin Casteels; AuthorSubject: Re: [FozzTexx/tcpser] Ivory BBS character encoding messed up at 2400 baud (#1)I already put in parity support. If your BBS is sending the wrong parity then you'll need to fix the BBS.
```

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by FozzTexx** [comment]
tcpser looks at the AT and the CR to determine the parity. If the BBS is sending any of those with the high bit set then tcpser is going to detect that the BBS wants to do 7 bits with parity.

**Comment by kcasteels** [comment]
```
                                                                                  Ok, I'll investigate further.  ‎I'll try and figure out what the BBS is sending over to tcpser. Thanks for your help.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: FozzTexxSent: Friday, July 22, 2016 17:17To: FozzTexx/tcpserReply To: FozzTexx/tcpserCc: Kevin Casteels; AuthorSubject: Re: [FozzTexx/tcpser] Ivory BBS character encoding messed up at 2400 baud (#1)tcpser looks at the AT and the CR to determine the parity. If the BBS is sending any of those with the high bit set then tcpser is going to detect that the BBS wants to do 7 bits with parity.
```

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Pinacolada64** [comment]
Hmm, @kcasteels would you mind sending me a copy too? Maybe we can work together on this. I wonder if we could use an Isepic cartridge to capture the program after it gets done decrypting itself. I proposed that solution to Rob Wright a day or so ago, think it would be worth it in order to investigate further?
