### ISSUE TITLE
Bug in debug due to switch from unsigned char to char

### ISSUE THREAD

**Issue by go4retro** [FozzTexx/tcpser#17]
because chars are signed, the trace code print routine will extend them out.  All but the last one get fixed, but the last one is signed extended:

2019-11-16 00:41:26:685744::RS->|0000|ff 0a ff 6f ff 69 ff ff 74 69 ff 65 ff ff 6f fffffff5|...o.i..ti.e..o.|
2019-11-16 00:41:26:685744::RS->|0010|74 ff ff 66 74 65 72 ff 36 30 ff ff 65 63 6f ffffffee|t..fter.60..eco.|

Notice all of the ff chars.  They aren't really ff, that's just the signed extended first two characters of the full 8 char value.  All but the last one get overwritten because of the "walk across the string by 3 positions pointer in the sprintf

trace really should not make assumptions about data sign, so really should be unsigned char* for the data stream. 

A quick fix is to do:

      sprintf(dptr + 5 + ((i % 16) * 3), "%2.2x", ch & 0xff);

on line 80, but I'm not sure that covers all the bases

**Comment by FozzTexx** [comment]
Fixed in 0d60ff0a6c64ba483b9d2c97182abea0a64eda55
