### ISSUE TITLE
Server socket could not be bound to port (Can't assign requested address)

### ISSUE THREAD

**Issue by Kirkman** [FozzTexx/tcpser#2]
I'm running into trouble trying to use your tcpser fork on my Mac (running macOS Sierra 10.12.1). 

First a little history. I have used tcpser4j in the past on my Mac to enable the use of terminal programs in the Hatari Atari ST emulator. tcpser4j has flaws, but it generally works.

Recently I have been trying Jim Brain's 1.0rc12 version of tcpser for linux. I can compile it, and it runs, but it doesn't seem to work as well as tcpser4j. When I connect to a BBS, I see the output from the BBS in my terminal, but ANSI detection seems to fail. When I try to type, nothing happens.

Anyway, that is what led me to want to try your fork. It compiles fine, but it fails with commands like `tcpser -v 25232  -s 38400 -l 7 -tsSiI`, which gives me this error:

`FATAL:Could not initialize ip232 server socket (Can't assign requested address)`

I don't know what's wrong, but I suspect the problem is in this part of `ip.c`:

```
    if (ip_addr != NULL) /* gwb */
      serverName.sin_addr.s_addr = inet_addr(ip_addr);
    else 
      serverName.sin_addr.s_addr = htonl(INADDR_ANY);
    serverName.sin_family = AF_INET;

    /* network-order */
    serverName.sin_port = htons(port);
```

If I replace that section with the original Jim Brain code, I don't get the error anymore:

```
    serverName.sin_addr.s_addr=htonl(INADDR_ANY);
    serverName.sin_family = AF_INET;

    /* network-order */
    serverName.sin_port = htons(port);
```

I can connect to a BBS. But from there it acts just like 1.0rc12 -- The BBS's ANSI detection fails and it gives me an ASCII welcome message. When it's time for me to type my username, nothing seems to happen.

**Comment by geneb** [comment]
The code you replaced allows you to specify what ip address to use if you're on a multi-homed host.

Keep in mind that the "-v" option was designed to be used with VICE (v1.19 I think).  Is that what you're doing with it?

**Comment by Kirkman** [comment]
I'm not using it with VICE, but with the Hatari Atari ST emulator. More description here: http://breakintochat.com/blog/2012/12/13/telnet-to-bbs-within-hatari-emulator/

**Comment by geneb** [comment]
Since git has decided to kick my ass today, I'm just going to post the fix here. :)
In ip.c where it used to read "if (ip_addr != NULL) /* gwb */" change the ip_addr != NULL to "strcmp(ip_addr, "") == 0"

In tcpser.c where it reads char *ip_addr = NULL, change it to ip_addr = "". 

Those two changes will fix the issue you've got with -v.  I wasn't aware that ip_init_server_conn() was being called twice and that's what caught me. :)

Unfortunately, I don't know squat about the Atari platform, so I'm not sure how to help with this particular issue.  If you've got Raspberry Pi handy, grab a null modem cable and a USB serial adapter and give that a shot.  It's how I'm connecting my Apple IIe to run Age of Reason. (aor.retroarchive.org, port 2300.)

**Comment by FozzTexx** [comment]
You only want to use the value of ip_addr if it's a zero length string? That doesn't seem right.

**Comment by geneb** [comment]
That's not what it does.  strcmp() compares the contents of ip_addr with "" and if they're equal, it returns 0.

g.

**Comment by FozzTexx** [comment]
You're checking to see if ip_addr is equal to "" and only if it is then you're going to do

  serverName.sin_addr.s_addr = inet_addr(ip_addr); 

and convert "" into an ip address.

**Comment by geneb** [comment]
Apparently i wasn't paying attention when I typed that in the reply.  the actual code reads:

 if (strcmp(ip_addr,"") != 0)  /* changed to strcmp test -04Mar17 gwb */

My apologies. :)

g.

**Comment by jgoerzen** [comment]
I think this change is relevant -- at least it fixed an issue for me:

`
--- a/src/ip232.c
+++ b/src/ip232.c
@@ -93,7 +93,7 @@ int ip232_init_conn(modem_config *cfg)
   LOG_ENTER();
   LOG(LOG_INFO, "Opening ip232 device");
   port = atoi(cfg->dce_data.tty);
-  rc = ip_init_server_conn("", port);
+  rc = ip_init_server_conn(NULL, port);
   if (rc < 0) {
     ELOG(LOG_FATAL, "Could not initialize ip232 server socket");
     exit(-1);
`

**Comment by jgoerzen** [comment]
bah, that formatting stank.  Anyhow, change "" to NULL in the call to ip_init_server_comm
