### ISSUE TITLE
"Talk/Data Switch" indication?

### ISSUE THREAD

**Issue by IBBBS** [FozzTexx/tcpser#20]
Running TCPSER on Linux (attempted FozzTexx / Jim Brain Master / 1.1.4)
Running x64sc and attempted both nc 127.0.0.1 25232 as well as just 127.0.0.1 25232
At TCP, running straight stick tcpser -v 25232 -p 6400 -s 1200 -i "k0" as well as no init string

BBS comes online and asks "MOVE T-D SWITCH TO DATA" - in the old days as I recall, this was a switch on the modem to go from "talking on the phone" to having modem attempt to communicate with whatever is online.

Calls from internet into TCPSER are seen and rings are generated, but bbs does not see modem in data mode.
Another thing - if using the setting without the NC portion, TCPSER reports "Link is up", but BBS still maintains we are in "talk" mode. 

TCPSER does report that server sockets are connected/listening, and that ip232 is configured. DTS:1 CTS:0 DCD:0
If I load a terminal program instead of the BBS, I am able to successfully dial out to a BBS on the internet, so pathway appears functional.

Any idea how to tell the "modem" we are in data mode?

**Comment by FozzTexx** [comment]
It sounds like your x64sc doesn't support the ip232 protocol so it's not seeing the carrier detect signal.
