### ISSUE TITLE
An improper locking bug in the log_trace

### ISSUE THREAD

**Issue by ycaibb** [FozzTexx/tcpser#24]
Hi, developers, in the below codes, when `i <0`, can it unlock at the `log_end()` a lock that is never acquired? I assumed that  `log_start();` and `log_end();` should be matched in a basic block just like in another place in the function `log_trace`?

https://github.com/FozzTexx/tcpser/blob/647cc1cb1036ab2c85160fa5fa17ba1e345f91da/src/debug.c#L88-L90
https://github.com/FozzTexx/tcpser/blob/647cc1cb1036ab2c85160fa5fa17ba1e345f91da/src/debug.c#L105-L108

```
void log_trace(int type, char *line, int len)
{
 ...;
      if ((i % 16) == 15) {
        log_start(LOG_TRACE);
        fprintf(log_file, "%s|%s|%s|", trace_type[type], data, text);
        log_end();
      }

    i = i % 16;
    if (i > 0) { // assume i<0
      for (; i < 16; i++) {
        sprintf(dptr + 5 + ((i % 16) * 3), "  ");
        if ((i % 16) != 15) {
          sprintf(dptr + 7 + ((i % 16) * 3), " ");
        }
        text[i % 16] = ' ';
      }
      log_start(LOG_TRACE);
      fprintf(log_file, "%s|%s|%s|", trace_type[type], data, text);
    }
    log_end(); // unlock a lock that is not acquired
  }
}
```

**Comment by go4retro** [comment]
I don't think unlocking a mutex which isn't active causes any issues, as I never see that error in the output, but you are correct that it should be aligned.  I think I did this to make absolutely sure the locks were always released at the end of the function, as if they got to this point (and you can assume len > 0), you'd have already acquired the lock at least once in the code.  For completeness, you cna add a log_end() to match the log_start(), but I think the extra log_end should stay, as the perror never fires, so giving a non existent lock back must be a soft error.

Jim

**Comment by ycaibb** [comment]
Hi, thank you very much for your reply and confirm this!
According to this [introduction](pthread_mutex_unlock()), unlocking a mutex that is not active could be a problem.
`The pthread_mutex_unlock() function unlocks the mutex specified. If the calling thread does not currently hold the mutex (via a previous call to pthread_mutex_lock(), pthread_mutex_trylock(), or pthread_mutex_timedlock_np()) the unlock request fails with the EPERM error.` I am just afraid it could be a problem one day due to unlocking an inactive mutex.

If the` log_start();` and `log_end();` could be aligned, it could be always ensured that the lock must be released before the function return to reach your goal, i.e., _make absolutely sure the locks were always released at the end of the function_.

Looking forward to more discussion.

**Comment by go4retro** [comment]
Since it's the only place log_end is not aligned, I'd make the change, turn logging on, test it, and submit a patch.

Jim
