### ISSUE TITLE
Fake modem

### ISSUE THREAD

**Issue by fredcwbr** [FozzTexx/tcpser#27]
How would i use tcpser as a fake modem ?
Ex.,    tcpser    /dev/ttyS0   /dev/tnt0    

[Discussion for reference](https://www.linuxquestions.org/questions/linux-networking-3/please-help-to-emulate-a-56k-connection-4175671379/)

Using a virtual serial like tty0tty as an example

Consider an example like this scenario happening:: 

LEGACYAPPLIANCE  <<-->> NULLMODEMCABLE TO RS232PORT [ttyS0] <---- [FAKEMODEM(emulated by tcpser)] --->  tnt0    ||||   tnt1  <--> mgetty

So when an appliance (legacy)  with a null modem cable  linked to the port  performs the connection 
  (DIAL, LOGIN,PPP, etc...) .. . it finds a compatible AT command modem on the other side , ...

**Comment by FozzTexx** [comment]
Read the instructions in the README.
