### ISSUE TITLE
Using TCPser on Windows 10 with BASH installed

### ISSUE THREAD

**Issue by WilliamBonner1** [FozzTexx/tcpser#9]
Hey there, I'm wanting to use my Windows 10 machine as a gateway for my Apple IIGS, but I'm getting an error.

46:~$ tcpser -s 9600 -d /dev/ttyUSB0
2017-07-27 11:20:21:488572736:FATAL:TTY /dev/ttyUSB0 could not be opened (No such file or directory)

not sure how to fix this, thanks! :)

**Comment by WilliamBonner1** [comment]
Oh forgot to mention. I have Ubuntu BASH installed on the Windows10 machine. I also have a USB to serial cable connected.

**Comment by FozzTexx** [comment]
I only use tcpser on Linux. /dev/ttyUSB0 is a Linux device name. Since you're using Windows you'll have to figure out if devices are even mapped to files.
